# Azure CLI を使った安定したデプロイメント
name: Build and deploy Node.js app to Azure Web App - aps-n2-01

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci
          echo "✅ Dependencies installed successfully"
      
      - name: Build Next.js app
        run: |
          echo "Building Next.js application..."
          npm run build
          echo "✅ Build completed successfully"
      
      - name: Create deployment zip
        run: |
          echo "Creating deployment package..."
          zip -r deploy.zip .next node_modules package*.json public next.config.js -x "node_modules/.cache/*"
          echo "✅ Deployment package created"
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4C24000BEE324F559E6C153082980F1A }}
      
      - name: Stop App Service (prevent conflicts)
        run: |
          az webapp stop --name aps-n2-01 --resource-group $(az webapp show --name aps-n2-01 --query resourceGroup -o tsv)
          echo "✅ App Service stopped"
      
      - name: Deploy to Azure Web App
        run: |
          az webapp deploy --name aps-n2-01 --resource-group $(az webapp show --name aps-n2-01 --query resourceGroup -o tsv) --src-path deploy.zip --type zip
          echo "✅ Deployment completed"
      
      - name: Start App Service
        run: |
          az webapp start --name aps-n2-01 --resource-group $(az webapp show --name aps-n2-01 --query resourceGroup -o tsv)
          echo "✅ App Service started"