# Single job workflow - artifact問題を回避
name: Build and deploy Node.js app to Azure Web App - aps-n2-01

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci
          echo "✅ Dependencies installed successfully"
      
      - name: Build Next.js app
        run: |
          echo "Building Next.js application..."
          npm run build
          echo "✅ Build completed successfully"
      
      - name: Verify build output
        run: |
          echo "Verifying build output..."
          ls -la .next/ || echo "❌ .next directory not found"
          ls -la package.json || echo "❌ package.json not found"
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'aps-n2-01'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4C24000BEE324F559E6C153082980F1A }}