# リトライ機能付き簡単ワークフロー
name: Build and deploy Node.js app to Azure Web App - aps-n2-01

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install and build
        run: |
          npm ci
          npm run build
      
      - name: Deploy to Azure Web App (Attempt 1)
        id: deploy1
        continue-on-error: true
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'aps-n2-01'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4C24000BEE324F559E6C153082980F1A }}
          clean: true
          restart: true
      
      - name: Wait and retry if first attempt failed
        if: steps.deploy1.outcome == 'failure'
        run: |
          echo "First deployment failed, waiting 60 seconds before retry..."
          sleep 60
      
      - name: Deploy to Azure Web App (Attempt 2)
        if: steps.deploy1.outcome == 'failure'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'aps-n2-01'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4C24000BEE324F559E6C153082980F1A }}
          clean: true
          restart: true