# 409 Conflictエラー対策版
name: Build and deploy Node.js app to Azure Web App - aps-n2-01

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci
          echo "✅ Dependencies installed successfully"
      
      - name: Build Next.js app
        run: |
          echo "Building Next.js application..."
          npm run build
          echo "✅ Build completed successfully"
      
      - name: Wait for any pending deployments
        run: |
          echo "Waiting 30 seconds to avoid deployment conflicts..."
          sleep 30
      
      - name: Deploy to Azure Web App (with retry)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'aps-n2-01'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4C24000BEE324F559E6C153082980F1A }}
          timeout: 600000
        env:
          AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4C24000BEE324F559E6C153082980F1A }}
      
      - name: Verify deployment
        run: |
          echo "Deployment completed. App URL: https://aps-n2-01.azurewebsites.net"
          curl -I https://aps-n2-01.azurewebsites.net || echo "Site not immediately available"